CREATE OR REPLACE FUNCTION
addme(int,int) RETURNS int AS 'MODULE_PATHNAME','addme'
LANGUAGE C STRICT;

CREATE OR REPLACE FUNCTION
multiply(int,int) RETURNS int AS 'MODULE_PATHNAME','multiply'
LANGUAGE C STRICT;
